### ISSUE TITLE
1.2.16 - Traducir Bloque de Código

### ISSUE THREAD

**Issue by adriaanbd** [adriaanbd/pythonpractico_ssg#2]

**Comment by valeriegmz** [comment]
Buenas tardes, mi nombre es Valerie Gómez. Soy estudiante de Ingeniería de sistemas de Información en la UTP y también estoy estudiando una licenciatura de inglés con énfasis en traducción en la Universidad Latina y me gustaría ayudar a traducir los códigos.

**Comment by adriaanbd** [comment]
Hola Valerie, gracias por mostrar interés en contribuir con traducciones. Empecemos con este entonces, ya te lo he asignado. Hazle un Fork al repositorio. Crea un nuevo branch con el nombre reprsentativo de lo que vas hacer `traduccion-1.2.16` o algun otro nombre y luego creas un PR contra el `dev` branch que voy a crear dentro de un rato. Si deseas que te explique o guie como hacer esto con Git, con gusto lo hago, solo avísame. Estoy en Discord `adriaanbd#9877` o email adriaanbd@gmail.com

**Comment by adriaanbd** [comment]
Closed by #45
